DELETE FROM NEWS_SOURCE;
INSERT INTO NEWS_SOURCE(ID, SOURCE_NAME, URL, ACTIVE_FLAG) VALUES (1, 'NRC', 'https://www.nrc.nl/rss/', 1);
INSERT INTO NEWS_SOURCE(ID, SOURCE_NAME, URL, ACTIVE_FLAG) VALUES (2, 'AD_AMSTERDAM', 'https://www.ad.nl/amsterdam/rss.xml', 1);
INSERT INTO NEWS_SOURCE(ID, SOURCE_NAME, URL, ACTIVE_FLAG) VALUES (3, 'VOLKSKRANT_WETENSCHAP', 'https://www.volkskrant.nl/wetenschap/rss.xml', 1);
INSERT INTO NEWS_SOURCE(ID, SOURCE_NAME, URL, ACTIVE_FLAG) VALUES (4, 'TROUW', 'https://www.trouw.nl/nieuws/rss.xml', 1);